// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: friend.proto

#include "friend.pb.h"
#include "friend.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace fixbug {

static const char* FiendServiceRpc_method_names[] = {
  "/fixbug.FiendServiceRpc/GetFriendsList",
};

std::unique_ptr< FiendServiceRpc::Stub> FiendServiceRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FiendServiceRpc::Stub> stub(new FiendServiceRpc::Stub(channel, options));
  return stub;
}

FiendServiceRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetFriendsList_(FiendServiceRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FiendServiceRpc::Stub::GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::fixbug::GetFriendsListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetFriendsList_, context, request, response);
}

void FiendServiceRpc::Stub::async::GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFriendsList_, context, request, response, std::move(f));
}

void FiendServiceRpc::Stub::async::GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetFriendsList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>* FiendServiceRpc::Stub::PrepareAsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fixbug::GetFriendsListResponse, ::fixbug::GetFriendsListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetFriendsList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>* FiendServiceRpc::Stub::AsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetFriendsListRaw(context, request, cq);
  result->StartCall();
  return result;
}

FiendServiceRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FiendServiceRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FiendServiceRpc::Service, ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FiendServiceRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fixbug::GetFriendsListRequest* req,
             ::fixbug::GetFriendsListResponse* resp) {
               return service->GetFriendsList(ctx, req, resp);
             }, this)));
}

FiendServiceRpc::Service::~Service() {
}

::grpc::Status FiendServiceRpc::Service::GetFriendsList(::grpc::ServerContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fixbug

