// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: friend.proto
#ifndef GRPC_friend_2eproto__INCLUDED
#define GRPC_friend_2eproto__INCLUDED

#include "friend.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace fixbug {

// 好友模块
class FiendServiceRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "fixbug.FiendServiceRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::fixbug::GetFriendsListResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>> AsyncGetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>>(AsyncGetFriendsListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>> PrepareAsyncGetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>>(PrepareAsyncGetFriendsListRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>* AsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendsListResponse>* PrepareAsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::fixbug::GetFriendsListResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>> AsyncGetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>>(AsyncGetFriendsListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>> PrepareAsyncGetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>>(PrepareAsyncGetFriendsListRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, std::function<void(::grpc::Status)>) override;
      void GetFriendsList(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>* AsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendsListResponse>* PrepareAsyncGetFriendsListRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendsListRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetFriendsList_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetFriendsList(::grpc::ServerContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFriendsList(::grpc::ServerContext* context, ::fixbug::GetFriendsListRequest* request, ::grpc::ServerAsyncResponseWriter< ::fixbug::GetFriendsListResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetFriendsList<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fixbug::GetFriendsListRequest* request, ::fixbug::GetFriendsListResponse* response) { return this->GetFriendsList(context, request, response); }));}
    void SetMessageAllocatorFor_GetFriendsList(
        ::grpc::MessageAllocator< ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFriendsList(
      ::grpc::CallbackServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetFriendsList<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFriendsList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFriendsList(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFriendsList(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFriendsList : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFriendsList() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fixbug::GetFriendsListRequest, ::fixbug::GetFriendsListResponse>* streamer) {
                       return this->StreamedGetFriendsList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFriendsList() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFriendsList(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendsListRequest* /*request*/, ::fixbug::GetFriendsListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFriendsList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fixbug::GetFriendsListRequest,::fixbug::GetFriendsListResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetFriendsList<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetFriendsList<Service > StreamedService;
};

}  // namespace fixbug


#endif  // GRPC_friend_2eproto__INCLUDED
